### ISSUE TITLE
Use a plugin key to generate the other values

### ISSUE THREAD

**Issue by markhowellsmead** [WPSwitzerland/plugin-builder#3]
e.g. the key my-great-plugin is entered and this is used for the folder and file names, as well as the text domain. Then also converted to PascalCase for the PHP namespace.

**Comment by markhowellsmead** [comment]
Plugin key: my-great-plugin (test this if we can: lowercase with dash (-) separators
Plugin namespace: MyGreatPlugin
File name: my-great-plugin.php
Folder name: my-great-plugin
Function prefix: my_great_plugin
Text domain: my-great-plugin

**Comment by maurobringolf** [comment]
We could additionally do the same for the author namespace, converting the authors name into CamelCase.

**Comment by markhowellsmead** [comment]
Good idea! This is a kickstarter, so the dev can always change the namespace manually if they need to.

**Comment by markhowellsmead** [comment]
Have you had a chance to look into this yet @maurobringolf?

**Comment by maurobringolf** [comment]
Not really,  I am more concerned with the cross-platform issues of ```sed```. I think if we provide such build scripts, we should make them work on MacOS and Linux. There seems to be a number of solutions but I dont really know whats best to use here. Here is a SO thread about this issue:

http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

**Comment by markhowellsmead** [comment]
I'm working on it myself right now. [This thread](http://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-x#34815955) (and help via WPCH) has helped a lot. It's a good exercise for me to start learning bash :)

**Comment by markhowellsmead** [comment]
Can you briefly re-write this snippet so that it searches and replaces within all files, not just specific files?

``find $PLUGIN_KEY -type f -name "*.php" -exec sed -i "s/PLUGIN_AUTHOR/$PLUGIN_AUTHOR/g" {} +``

**Comment by markhowellsmead** [comment]
It's OK, I've got it :) #RTFM

**Comment by markhowellsmead** [comment]
New version (0.2.1) almost complete: adding a AUTHOR_URI or PLUGIN_URI with a http:// or https:// prefix breaks it.

**Comment by markhowellsmead** [comment]
Ref #2 for the last fix.
